# Generated by Django 3.2.7 on 2021-11-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0003_auto_20211126_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Имя, Отчество'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(max_length=100, verbose_name='Профессия, должность'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Полное ФИО'),
        ),
    ]
